[package]
name = "hello-world"
version = "0.1.0"
authors = ["Joern Bernhardt <joern.bernhardt@googlemail.com>"]

[dependencies]
repeat = { path = "../repeat" }
is-palindrome = { path = "../is-palindrome" }
hyper = "0.12"
